### ISSUE TITLE
TADpole issues

### ISSUE THREAD

**Issue by DonQwerty** [3DGenomes/TADpole#1] opened 2019-07-22 14:28 UTC
Very good work! 
Could you add to the TADpole function the option for reading matrices with header? Using maybe the "skip" variable of the "read.big.matrix" function (in my version, tadbit generates a matrix with header and i didnt know which was my error).

And also i have tried to generate the TADs for one chromosome and the result is strange. My matrix has 4750 bins but the last TAD finishes in the bin 4489 and i dont know if it is correct or not (because there is data in those lost bins). 

![prueba_matrix2](https://user-images.githubusercontent.com/13988816/61640381-7e47fa00-ac9d-11e9-9297-c99c231292e0.png)

Thank you for all

**Comment by paulasoler** [comment] 2019-07-22 16:24
Thanks for the feedback!
Regarding the first issue, yes, that's indeed a good idea and we are definitely looking into it. We'll let you know when it's done.
As for the mismatch in the results, we would need to reproduce the bug in order to understand what happened. Is there a way we can have access to the data and the commands you used to generate this result?
Thanks!

**Comment by DonQwerty** [comment] 2019-07-23 08:24
Yes of course!
It happens also with the same matrix with a lower resolution (50kb)

[norm_chr17_50kb.tar.gz](https://github.com/3DGenomes/TADpole/files/3420947/norm_chr17_50kb.tar.gz)

![prueba_matrix3](https://user-images.githubusercontent.com/13988816/61695364-aaae5580-ad33-11e9-9fc6-3c5c4653821e.png)

Thank you

**Comment by paulasoler** [comment] 2019-07-23 18:53
Hi DonQwerty,
TADpole flags the bad columns of the matrix (columns with an abnormally low signal) before the analysis proper. It turns out we were losing this information at some point in the script, so the plotting function could not adjust the image to account for those bad columns.
In summary, the TAD call was right but the plot was wrong.
It should be fixed now in the development repo (https://github.com/paulasoler/TADpole), and will soon be pulled to this repo.
We are also working on the header-skipping part.
Thanks! ;)

**Closed as completed** 2019-07-23 18:53 UTC
